---
title: "About"
---

## In short

{{< fa user-graduate >}} : MS-Data Science & AI | MPH-Epidemiology | MBA-Healthcare Administration | BHMS

{{< fa envelope title="An envelope" >}} : bhoite.prasad@gmail.com

{{< fa heart title="A Heart">}} : Telling the story and meaningful insights out of data


## Hi 👋 , I'm Prasad

I am a Lead Data Scientist at Herbert Wertheim College of Medicine, Florida Intarnational University, Miami, USA.

## Education

MS- Data Science & AI \| Florida International University, Miami, FL \|  Aug 2019 - Apr 2022

MPH-Epidemiology \| Florida International University, Miami, FL \|  Aug 2019 - Apr 2022

MBA-Healthcare Administration \| School of Healthcare Administration, Pune, India \| Aug 2014 - Jul 2016

Bachelor of Homoeopathic Medicine & Surgery \| L.M.F.'s Homoeopathic Medical College, Pune, India \| Aug 2003 - Jul 2009

## Experience

Lead Data Scientist \| Herbert Wertheim College of Medicine, FIU \| Jun 2016 - present

Graduate Research Assistant \| Office of Analysis & Information Management, FIU \| Apr 2015 - Jun 2016

Research Assistant \| Department of Epidemiology, Robert Stempel College of Public Health & Social Work, FIU \| Sept 2015 - Jun 2016

Student Assistant \| Herbert Wertheim College of Medicine, FIU \| Oct 2014 - Apr 2015

Clinical Assistant \| "Prayas" Amrita Clinic, Pune, MH, India \| May 2009 - Jul 2014

Resident \| Mankar Pediatric Hospital, Pune, MH, India \| Jan 2009 - Dec 2009

Resident \| Madhukar Genera Hospital, Pune, MH, India \| Jul 2008 - Dec 2008
